"""Added user and mindmap tables

Revision ID: 692db706b565
Revises: bdc5038b4957
Create Date: 2025-02-12 17:53:31.676574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692db706b565'
down_revision: Union[str, None] = 'bdc5038b4957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mindmaps', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('mindmaps', 'data',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_mindmaps_title'), 'mindmaps', ['title'], unique=False)
    op.drop_constraint('mindmaps_user_id_fkey', 'mindmaps', type_='foreignkey')
    op.create_foreign_key(None, 'mindmaps', 'users', ['owner_id'], ['id'])
    op.drop_column('mindmaps', 'user_id')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('mindmaps', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mindmaps', type_='foreignkey')
    op.create_foreign_key('mindmaps_user_id_fkey', 'mindmaps', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_mindmaps_title'), table_name='mindmaps')
    op.alter_column('mindmaps', 'data',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('mindmaps', 'owner_id')
    # ### end Alembic commands ###
